services:
  # Base de datos PostgreSQL para PaperShop
  papershop-pg-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: papershop-pg-db-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PGSQL_PORT_PUBLIC}:5432
    volumes:
      - papershop-pg-data:/var/lib/postgresql/data
      #- ./init_db/init_papershop.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      papershop-network:
        ipv4_address: 172.22.0.251
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Adminer para gestión web de la BD
  papershop-adminer-db:
    image: adminer
    container_name: papershop-adminer-container
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - papershop-pg-db
    networks:
      papershop-network:
        ipv4_address: 172.22.0.253

  # pgAdmin para gestión avanzada
  papershop-pgadmin4-db:
    container_name: papershop-pgadmin4-container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@papershop.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - 16543:80
    depends_on:
      - papershop-pg-db
    networks:
      papershop-network:
        ipv4_address: 172.22.0.254

networks:
  papershop-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24

volumes:
  papershop-pg-data:
    name: papershop-pg-data-local
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_DATA_DIR_BD}
      o: bind